version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Synthesizing CDK..."
      - cdk synth -o cdk.out --asset-metadata

artifacts:
  files:
    - DailyMoodTrackerStack.template.json
  base-directory: cdk.out

cache:
  paths:
    - node_modules/**/* 
