version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt
  build:
    commands:
      - cdk synth -o cdk.out
artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
