version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt
  build:
    commands:
      - cdk synth
artifacts:
  files:
    - '**/*'
    - 'cdk.out/DailyMoodTrackerStackJJ8876281.template.json'
