version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - pip install -r requirements.txt
      - npm install -g aws-cdk  
  build:
    commands:
      - echo "Synthesizing CDK app..."
      - cdk synth -o cdk.out
      - ls -la cdk.out  

artifacts:
  base-directory: cdk.out
  files:
    - DailyMoodTrackerStack.template.json  
