version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Verifying lambda directory structure"
      - ls -la lambda/
      - echo "CDK version:"
      - cdk --version
  build:
    commands:
      - cdk synth -o cdk.out --verbose
artifacts:
  files:
    - '**/*'
  base-directory: cdk.out